name: kivy-ios

on: [push, pull_request]

jobs:

  build_python3_kivy:
    runs-on: 'macos-latest'
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        brew install autoconf wget
    - name: Build libffi
      run: |
        wget https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz
        tar -xvf libffi-3.4.4.tar.gz
        cd libffi-3.4.4
        ./generate-darwin-source-and-headers.py --only-osx